import pandas as pd

dataset = pd.read_csv('bestsellers.csv')

print(dataset.head(5))
print()
print("--------------")
print()
print(len(dataset.index))
print()
print("--------------")
print()
print(dataset.index.names)
print()
print("--------------")
print()
print(dataset.columns)
print()
print("--------------")
print()
print(len(dataset.columns))
print()
print("--------------")
print()
print(dataset["Price"].mean())
print()
print("--------------")
print()
print(dataset["Price"].max())
print()
print("--------------")
print()
print(dataset["Price"].min())
print()
print("--------------")
print()
print(dataset["Author"].nunique())
print()
print("--------------")
print()
print(dataset["Year"].nunique())
print()
print("--------------")
print()
print(dataset["Name"])
print()
print("--------------")
print()
print(dataset.loc[1])
print()
print("--------------")
print()
print(dataset[(dataset["Year"] > 2010) & (dataset["Price"] > 25)])
print()
print("--------------")
print()
print(dataset[(dataset["Year"] > 2010) | (dataset["Price"] > 25)])
print()
print("--------------")
print()
print(dataset[dataset["Price"] == dataset["Price"].max()]["Name"])
print()
print("--------------")
print()
print(dataset[dataset["Price"] == dataset["Price"].min()]["Name"])
print()
print("--------------")
print()
print(dataset[dataset["Author"] == "JJ Smith"]["Name"])
print()
print("--------------")
print()
print(dataset[dataset["Name"] == "10-Day Green Smoothie Cleanse"]["Author"])
print()
print("--------------")
print()
print(dataset.groupby("Year").mean())
print()
print("--------------")
print()
print(dataset.sort_values("Price"))
print()
print("--------------")
print()
print(dataset.sort_values("Price",ascending=False))
print()
print("--------------")
print()
print(dataset.pivot_table)
print()
print("--------------")
print()


